package dbnp.transcriptomics.data
/**
 * The Chip entity.
 * Author
 * drs. Robert Kerkhoven
 * robert_kerkhoven@hotmail.com
 * robert.kerkhoven@wur.nl
 *
 * Generated by the Grails Appliation Generator
 *
 */
class ChipAnnotation {
    static mapping = {
         table 'chip_annotation'
         // version is set to false, because this isn't available by default for legacy databases
         version false
         id generator:'identity', column:'id'
         chipIdChip column:'chip_id'
    }
    Integer id
    String probeset
    String accession
    String geneSymbol
    String description
    Integer listPos
    // Relation
    Chip chipIdChip

    static constraints = {
        id(max: 2147483647)
        probeset(size: 1..50, blank: false)
        accession(size: 0..45)
        geneSymbol(size: 0..45)
        description(size: 0..300)
        listPos(max: 2147483647)
        chipIdChip()
    }
    String toString() {
        return "${id}" 
    }
}
