package dbnp.transcriptomics.data
/**
 * The Chip entity.
 * Author
 * drs. Robert Kerkhoven
 * robert_kerkhoven@hotmail.com
 * robert.kerkhoven@wur.nl
 *
 * Generated by the Grails Appliation Generator
 *
 */
class Chip {
    static mapping = {
         table 'chip'
         // version is set to false, because this isn't available by default for legacy databases
         version false
         id generator:'identity', column:'id'
    }
    Integer id
    String name
    Date timeStamp
    String databaseName
    String organismName

    static constraints = {
        id(max: 2147483647)
        name(size: 0..200)
        timeStamp()
        databaseName(size: 0..45)
        organismName(size: 0..100)
    }
    String toString() {
        return "${id}" 
    }
}
