/**
 * The Chip entity.
 * Author
 * drs. Robert Kerkhoven
 * robert_kerkhoven@hotmail.com
 * robert.kerkhoven@wur.nl
 *
 * Generated by the Grails Appliation Generator
 *
 */
class Expression {
    static mapping = {
         table 'expression'
         // version is set to false, because this isn't available by default for legacy databases
         version false
         id generator:'identity', column:'id'
         annotationIdChipAnnotation column:'annotation_id'
    }
    Integer id
    Integer studySampleAssayId
    Double expression
    // Relation
    ChipAnnotation annotationIdChipAnnotation

    static constraints = {
        id(max: 2147483647)
        studySampleAssayId(max: 2147483647)
        expression()
        annotationIdChipAnnotation()
    }
    String toString() {
        return "${id}" 
    }
}
